### ISSUE TITLE
Try to avoid the Serial.println() in a interrupt routine.

### ISSUE THREAD

**Issue by Koepel** [BasOnTech/Arduino-Beginners-NL#1]
In the file "rotary-encoder-deel-2.ino" the Serial functions are used in a interrupt routine. That can start a lot of problems, since the Serial library uses interrupts itself.

Keep an interrupt routine as small and as short as possible. Try to avoid the use of Serial functions in a interrupt routine. It might have different results for different Arduino boards, so it is better to avoid those problems completely.

**Comment by basvdijk** [comment]
This is what I explain in the video at https://youtu.be/tmYPuIvSdrg?t=11m56s. I'll add a comment to the code to emphasise this even more. Thanks!

**Comment by Koepel** [comment]
Very good. I had the video running in the background and was probably not listening to everything. Sorry.

A major problem is that the Serial library uses interrupts to transmit data. Those interrupts do not run in a other interrupt routine by default. When there is a burst of interrupts and a lot of Serial.println(), the Serial TX buffer might get full. Then the Serial functions will wait for an empty place in the Serial TX buffer, but that will never happen and the code halts in the interrupt routine.

**Comment by basvdijk** [comment]
Thanks for the additional info, de waarschuwing staat op https://github.com/BasOnTech/Arduino-Beginners-NL/blob/master/rotary-encoder/rotary-encoder-deel-2.ino#L59
