### ISSUE TITLE
Tekening les2 klopt niet

### ISSUE THREAD

**Issue by MHolkamp** [BasOnTech/Arduino-Beginners-NL#3]
Op de tekening staat de verbindingsdraad op pin 12, maar dat moet pin 13 zijn.

**Comment by basvdijk** [comment]
@MHolkamp Thanks voor het doorgeven! 👍🏻

**Comment by MHolkamp** [comment]
Hoi Bas,

Tekening bij les 18 ook niet btw
Daar staat de tekening van 17 denk ik.

Met vriendelijke groeten / Best regards / Mit freundlichen Grüße
Martin Holkamp

We hebben de wereld niet geërfd van onze ouders, maar te leen van onze kinderen,
We do not inherit the Earth from our parents; we borrow it from our Children.

Op 31 december 2019 bij 16:07:03, osi (notifications@github.com) schreef:

@MHolkamp Thanks voor het doorgeven! 👍🏻
